In [1]:
import pandas as pd

df = pd.read_csv("C:/Users/natch/Downloads/Amazon Sale Report/Amazon Sale Report.csv")
print(df.shape)
print(df.columns.tolist())

(128975, 24)
['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

C:\Users\natch\AppData\Local\Temp\ipykernel_20320\3584795471.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/natch/Downloads/Amazon Sale Report/Amazon Sale Report.csv")

In [2]:
import pandas as pd

df = pd.read_csv(
    "C:/Users/natch/Downloads/Amazon Sale Report/Amazon Sale Report.csv",
    low_memory=False
)

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB
None

In [3]:
df.isnull().sum().sort_values(ascending=False)

fulfilled-by          89698
promotion-ids         49153
Unnamed: 22           49050
currency               7795
Amount                 7795
Courier Status         6872
ship-country             33
ship-postal-code         33
ship-state               33
ship-city                33
ship-service-level        0
Style                     0
Date                      0
B2B                       0
Status                    0
Fulfilment                0
Sales Channel             0
Qty                       0
Order ID                  0
ASIN                      0
Size                      0
Category                  0
SKU                       0
index                     0
dtype: int64

In [4]:
print(df['Unnamed: 22'].value_counts(dropna=False).head(20))

Unnamed: 22
False    79925
NaN      49050
Name: count, dtype: int64

In [5]:
print(df['fulfilled-by'].value_counts(dropna=False))

fulfilled-by
NaN          89698
Easy Ship    39277
Name: count, dtype: int64

In [6]:
print(df['currency'].value_counts(dropna=False))

currency
INR    121180
NaN      7795
Name: count, dtype: int64

In [7]:
df[df['Amount'].isnull()][
    ['Status', 'Qty', 'Amount', 'currency']
].head(20)

        Status  Qty  Amount currency
8    Cancelled    0     NaN      NaN
29   Cancelled    0     NaN      NaN
65   Cancelled    0     NaN      NaN
84   Cancelled    0     NaN      NaN
95   Cancelled    0     NaN      NaN
101  Cancelled    0     NaN      NaN
132  Cancelled    0     NaN      NaN
139  Cancelled    0     NaN      NaN
155  Cancelled    0     NaN      NaN
165  Cancelled    0     NaN      NaN
205  Cancelled    0     NaN      NaN
215  Cancelled    0     NaN      NaN
242  Cancelled    0     NaN      NaN
249  Cancelled    0     NaN      NaN
250  Cancelled    0     NaN      NaN
271  Cancelled    0     NaN      NaN
328  Cancelled    0     NaN      NaN
363  Cancelled    0     NaN      NaN
381  Cancelled    0     NaN      NaN
413  Cancelled    0     NaN      NaN

In [8]:
df[df['Amount'].isnull()]['Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [9]:
df[
    (df['Amount'].isnull()) &
    (df['Status'] != 'Cancelled')
][
    ['Order ID',
     'Status',
     'Qty',
     'Category',
     'Amount']
].head(30)

                  Order ID   Status  Qty       Category  Amount
937    S02-5278980-4327051  Shipped   15         Blouse     NaN
1057   S02-9107114-0460608  Shipped    2            Set     NaN
1615   405-7790745-1369118  Shipped    0          kurta     NaN
1989   171-9673855-2321133  Shipped    0            Set     NaN
2424   404-7478762-7926753  Shipped    0            Set     NaN
2819   404-0814480-8157169  Shipped    0          kurta     NaN
3631   S02-1006261-5356758  Shipped    9          kurta     NaN
3632   S02-3681731-6111841  Shipped    1          kurta     NaN
3634   S02-1926028-4838217  Shipped    1          kurta     NaN
3636   S02-6828927-1180856  Shipped   13          kurta     NaN
3637   S02-3409426-0744131  Shipped    2         Blouse     NaN
3886   S02-8357726-8633940  Shipped    1            Set     NaN
3887   S02-6358630-3384547  Shipped    1         Blouse     NaN
3888   S02-8920429-3367507  Shipped    1            Set     NaN
3889   S02-0827522-8659612  Shipped    1            Set     NaN
3890   S02-7924344-3280541  Shipped    1          kurta     NaN
3891   S02-7832149-5714447  Shipped    1          kurta     NaN
3892   S02-9649067-3246849  Shipped    1          kurta     NaN
3893   S02-2310917-8166336  Shipped    1          kurta     NaN
3894   S02-0668744-7285638  Shipped    1            Set     NaN
9255   405-1892033-5435562  Shipped    0            Set     NaN
11145  404-7498280-7477149  Shipped    0            Set     NaN
13460  S02-0835825-7267219  Shipped    1            Set     NaN
13716  S02-7568319-2142153  Shipped    1  Western Dress     NaN
13718  S02-9236057-6330320  Shipped    1          kurta     NaN
13719  S02-3986693-8942048  Shipped    1          kurta     NaN
13721  S02-4244793-3107843  Shipped    1            Set     NaN
13722  S02-7889185-5931306  Shipped    1            Set     NaN
13725  S02-0764737-6642956  Shipped    1          kurta     NaN
13729  S02-5277297-0167425  Shipped    1            Set     NaN

In [10]:
df['Status'].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [11]:
df_clean = df.copy()

df_clean = df_clean.drop(columns=['Unnamed: 22'])

df_clean = df_clean[
    ~(
        (df_clean['Amount'].isnull()) &
        (df_clean['Status'] != 'Cancelled')
    )
]

In [12]:
df_clean['Order ID'].nunique()

120255

In [13]:
len(df_clean)

128746

In [14]:
df_clean[['Order ID','SKU']].duplicated().sum()

np.int64(6)

In [15]:
duplicates = df_clean[
    df_clean[['Order ID','SKU']].duplicated(keep=False)
]

duplicates.sort_values(['Order ID','SKU'])

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
85790,85790,171-3249942-2207542,05-03-22,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,...,1,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
85791,85791,171-3249942-2207542,05-03-22,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,...,1,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
79844,79844,171-9628368-5329958,05-07-22,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,...,0,NaN,NaN,ERNAKULAM,KERALA,682017.0,IN,NaN,False,NaN
79845,79845,171-9628368-5329958,05-07-22,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,...,0,NaN,NaN,ERNAKULAM,KERALA,682017.0,IN,NaN,False,NaN
86418,86418,405-8669298-3850736,05-03-22,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,...,1,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
86419,86419,405-8669298-3850736,05-03-22,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,...,1,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
30660,30660,406-0372545-6086735,04-12-22,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,...,0,NaN,NaN,Siliguri,WEST BENGAL,734008.0,IN,NaN,False,NaN
30661,30661,406-0372545-6086735,04-12-22,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,...,0,NaN,NaN,Siliguri,WEST BENGAL,734008.0,IN,NaN,False,NaN
98954,98954,407-4853873-4978725,06-22-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,...,1,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
98955,98955,407-4853873-4978725,06-22-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,...,1,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
41291,41291,408-0373839-4433120,04-05-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,...,0,NaN,NaN,BENGALURU,KARNATAKA,560072.0,IN,NaN,False,NaN
41292,41292,408-0373839-4433120,04-05-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,...,0,NaN,NaN,BENGALURU,KARNATAKA,560072.0,IN,NaN,False,NaN

In [16]:
df_clean['Date'].head(10)

0    04-30-22
1    04-30-22
2    04-30-22
3    04-30-22
4    04-30-22
5    04-30-22
6    04-30-22
7    04-30-22
8    04-30-22
9    04-30-22
Name: Date, dtype: object

In [17]:
df_clean['Date'].tail(10)

128965    05-31-22
128966    05-31-22
128967    05-31-22
128968    05-31-22
128969    05-31-22
128970    05-31-22
128971    05-31-22
128972    05-31-22
128973    05-31-22
128974    05-31-22
Name: Date, dtype: object

In [18]:
df_clean = df_clean.drop_duplicates()

In [19]:
df_clean[['Order ID','SKU']].duplicated().sum()

np.int64(6)

In [20]:
df_clean['Order_Date'] = pd.to_datetime(
    df_clean['Date'],
    format='%m-%d-%y'
)

In [21]:
df_clean['Order_Date'].head()

0   2022-04-30
1   2022-04-30
2   2022-04-30
3   2022-04-30
4   2022-04-30
Name: Order_Date, dtype: datetime64[ns]

In [22]:
print(df_clean['Order_Date'].min())
print(df_clean['Order_Date'].max())

2022-03-31 00:00:00
2022-06-29 00:00:00

In [23]:
df_clean['Order_Date'].dt.month_name().value_counts().sort_index()

Order_Date
April    48976
June     37632
March      170
May      41968
Name: count, dtype: int64

In [24]:
df_clean = df_clean.drop_duplicates()

In [25]:
df_clean[['Order ID','SKU']].duplicated().sum()

np.int64(6)

In [26]:
df_clean[df_clean[['Order ID','SKU']].duplicated(keep=False)] \
    .sort_values(['Order ID','SKU'])

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Order_Date
85790,85790,171-3249942-2207542,05-03-22,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,...,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,2022-05-03
85791,85791,171-3249942-2207542,05-03-22,Shipped,Amazon,Amazon.in,Expedited,SET323,SET323-KR-NP-XL,Set,...,INR,939.0,PUNE,MAHARASHTRA,411057.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,2022-05-03
79844,79844,171-9628368-5329958,05-07-22,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,...,NaN,NaN,ERNAKULAM,KERALA,682017.0,IN,NaN,False,NaN,2022-05-07
79845,79845,171-9628368-5329958,05-07-22,Cancelled,Amazon,Amazon.in,Expedited,J0329,J0329-KR-L,kurta,...,NaN,NaN,ERNAKULAM,KERALA,682017.0,IN,NaN,False,NaN,2022-05-07
86418,86418,405-8669298-3850736,05-03-22,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,...,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,2022-05-03
86419,86419,405-8669298-3850736,05-03-22,Shipped,Amazon,Amazon.in,Expedited,MEN5025,MEN5025-KR-XXXL,kurta,...,INR,533.0,GHAZIABAD,UTTAR PRADESH,201010.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,2022-05-03
30660,30660,406-0372545-6086735,04-12-22,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,...,NaN,NaN,Siliguri,WEST BENGAL,734008.0,IN,NaN,False,NaN,2022-04-12
30661,30661,406-0372545-6086735,04-12-22,Cancelled,Amazon,Amazon.in,Expedited,SET197,SET197-KR-NP-L,Set,...,NaN,NaN,Siliguri,WEST BENGAL,734008.0,IN,NaN,False,NaN,2022-04-12
98954,98954,407-4853873-4978725,06-22-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,...,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,2022-06-22
98955,98955,407-4853873-4978725,06-22-22,Shipped,Amazon,Amazon.in,Expedited,J0230,J0230-SKD-M,Set,...,INR,1163.0,Zirakpur,Punjab,140603.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,2022-06-22
41291,41291,408-0373839-4433120,04-05-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,...,NaN,NaN,BENGALURU,KARNATAKA,560072.0,IN,NaN,False,NaN,2022-04-05
41292,41292,408-0373839-4433120,04-05-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3501,JNE3501-KR-M,kurta,...,NaN,NaN,BENGALURU,KARNATAKA,560072.0,IN,NaN,False,NaN,2022-04-05

In [27]:
print("Rows before:", len(df_clean))

df_test = df_clean.drop_duplicates()

print("Rows after:", len(df_test))

Rows before: 128746
Rows after: 128746

In [28]:
df_clean.duplicated().sum()

np.int64(0)

In [29]:
df_clean['Qty'].describe()

count    128746.000000
mean          0.904750
std           0.307163
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           8.000000
Name: Qty, dtype: float64

In [30]:
df_clean['Amount'].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [31]:
df_clean['Qty'].value_counts().sort_index().head(20)

Qty
0     12701
1    115666
2       337
3        31
4         8
5         2
8         1
Name: count, dtype: int64

In [32]:
df_clean[df_clean['Qty']==0]['Status'].value_counts()

Status
Cancelled    12701
Name: count, dtype: int64

In [33]:
df_clean[df_clean['Amount']==0][
    ['Status','Qty','Amount']
].value_counts()

Status                         Qty  Amount
Shipped                        1    0.0       1518
Shipped - Delivered to Buyer   1    0.0        716
Shipped - Returned to Seller   1    0.0         51
Shipped - Picked Up            1    0.0         28
Pending                        1    0.0         17
Pending - Waiting for Pick Up  1    0.0          9
Shipped - Lost in Transit      1    0.0          2
Shipped - Returning to Seller  1    0.0          2
Name: count, dtype: int64

In [34]:
df_clean[df_clean['Amount']==0][
    ['Order ID',
     'Order_Date',
     'Category',
     'SKU',
     'Qty',
     'Amount',
     'Status',
     'promotion-ids']
].head(20)

,Order ID,Order_Date,Category,SKU,Qty,Amount,Status,promotion-ids
212,408-4547464-4180323,2022-04-30,kurta,JNE3568-KR-XXL,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
374,408-5020509-5674715,2022-04-30,Western Dress,JNE3798-KR-M,1,0.0,Shipped - Returned to Seller,Amazon PLCC Free-Financing Universal Merchant ...
385,408-3137526-3167563,2022-04-30,kurta,JNE3405-KR-L,1,0.0,Shipped,NaN
388,408-7971979-8745937,2022-04-30,Western Dress,J0401-DR-XS,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
392,408-0912805-7526753,2022-04-30,Set,SET365-KR-NP-L,1,0.0,Shipped,NaN
436,408-6466311-6949931,2022-04-30,Set,SET014-KR-PP-XXL,1,0.0,Shipped,NaN
441,408-6732772-4525113,2022-04-30,Set,J0010-LCD-XS,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
446,408-7937211-8974712,2022-04-30,Set,SET324-KR-NP-L,1,0.0,Shipped,NaN
449,408-6348199-2089932,2022-04-30,Set,J0283-SET-XL,1,0.0,Shipped,NaN
729,408-4193711-8156307,2022-04-30,Blouse,J0215-BL-L,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
731,408-0902233-8069950,2022-04-30,kurta,JNE3714-KR-L,1,0.0,Shipped - Returned to Seller,Amazon PLCC Free-Financing Universal Merchant ...
827,408-9407260-0749114,2022-04-30,kurta,JNE3463-KR-L,1,0.0,Shipped,NaN
844,408-5118229-6373917,2022-04-30,kurta,JNE3399-KR-XL,1,0.0,Shipped,NaN
930,408-6069754-7397924,2022-04-30,kurta,JNE3805-KR-S,1,0.0,Shipped,NaN
947,408-8489677-5577933,2022-04-30,kurta,MEN5004-KR-XL,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
986,408-2548158-8811519,2022-04-30,Set,SET342-KR-NP-N-XXL,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
1071,408-0466342-6160313,2022-04-30,Western Dress,J0158-DR-XL,1,0.0,Shipped,NaN
1104,408-3011835-7100318,2022-04-30,kurta,JNE3730-KR-XL,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...
1115,408-7721306-8516366,2022-04-30,kurta,JNE3405-KR-L,1,0.0,Shipped,NaN
1226,408-5393823-3123507,2022-04-30,kurta,JNE2171-KR-437-L,1,0.0,Shipped - Delivered to Buyer,Amazon PLCC Free-Financing Universal Merchant ...

In [35]:
len(df_clean[df_clean['Amount']==0])

2343

In [36]:
round(
    len(df_clean[df_clean['Amount']==0])
    / len(df_clean) * 100,
    2
)

1.82

In [37]:
df_clean['fulfilled-by'].value_counts(dropna=False)

fulfilled-by
NaN          89480
Easy Ship    39266
Name: count, dtype: int64

In [38]:
df_clean['Sales Channel '].value_counts(dropna=False)

Sales Channel
Amazon.in     128745
Non-Amazon         1
Name: count, dtype: int64

In [39]:
df_clean['Fulfilment'].value_counts(dropna=False)

Fulfilment
Amazon      89480
Merchant    39266
Name: count, dtype: int64

In [40]:
pd.crosstab(df_clean['Fulfilment'], df_clean['fulfilled-by'], dropna=False)

fulfilled-by  Easy Ship    NaN
Fulfilment
Amazon                0  89480
Merchant          39266      0

In [41]:
df_clean = df_clean.drop(columns=['fulfilled-by'])

In [42]:
df_clean['ship-city'] = df_clean['ship-city'].str.title()
df_clean['ship-state'] = df_clean['ship-state'].str.title()

In [43]:
df_clean['ship-country'].value_counts()

ship-country
IN    128713
Name: count, dtype: int64

In [44]:
df_clean['Category'].value_counts()

Category
Set              50180
kurta            49777
Western Dress    15491
Top              10612
Ethnic Dress      1158
Blouse             922
Bottom             439
Saree              164
Dupatta              3
Name: count, dtype: int64

In [45]:
df_clean['Courier Status'].value_counts(dropna=False)

Courier Status
Shipped      109487
NaN            6861
Unshipped      6558
Cancelled      5840
Name: count, dtype: int64

In [46]:
df_clean['ship-country'] = df_clean['ship-country'].fillna('IN')
df_clean['Category'] = df_clean['Category'].str.title()

In [47]:
df_clean[df_clean['Courier Status'].isnull()]['Status'].value_counts()

Status
Cancelled    6861
Name: count, dtype: int64

In [48]:
df_clean['ship-city'] = df_clean['ship-city'].str.title()
df_clean['ship-state'] = df_clean['ship-state'].str.title()

In [49]:
df_clean['Courier Status'] = df_clean['Courier Status'].fillna('Not Assigned')

In [50]:
df_clean = df_clean.drop(
    columns=[
        'Sales Channel ',
        'currency',
        'promotion-ids'
    ]
)

In [51]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 128746 entries, 0 to 128974
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128746 non-null  int64
 1   Order ID            128746 non-null  object
 2   Date                128746 non-null  object
 3   Status              128746 non-null  object
 4   Fulfilment          128746 non-null  object
 5   ship-service-level  128746 non-null  object
 6   Style               128746 non-null  object
 7   SKU                 128746 non-null  object
 8   Category            128746 non-null  object
 9   Size                128746 non-null  object
 10  ASIN                128746 non-null  object
 11  Courier Status      128746 non-null  object
 12  Qty                 128746 non-null  int64
 13  Amount              121180 non-null  float64
 14  ship-city           128713 non-null  object
 15  ship-state          128713 non-null  object
 16  ship-postal-code    128713 non-null  float64
 17  ship-country        128746 non-null  object
 18  B2B                 128746 non-null  bool
 19  Order_Date          128746 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(2), int64(2), object(14)
memory usage: 19.8+ MB

In [52]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('-', '_')
)

In [53]:
df_clean = df_clean.drop(columns=['index'])
df_clean.reset_index(drop=True, inplace=True)

In [54]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128746 entries, 0 to 128745
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            128746 non-null  object
 1   date                128746 non-null  object
 2   status              128746 non-null  object
 3   fulfilment          128746 non-null  object
 4   ship_service_level  128746 non-null  object
 5   style               128746 non-null  object
 6   sku                 128746 non-null  object
 7   category            128746 non-null  object
 8   size                128746 non-null  object
 9   asin                128746 non-null  object
 10  courier_status      128746 non-null  object
 11  qty                 128746 non-null  int64
 12  amount              121180 non-null  float64
 13  ship_city           128713 non-null  object
 14  ship_state          128713 non-null  object
 15  ship_postal_code    128713 non-null  float64
 16  ship_country        128746 non-null  object
 17  b2b                 128746 non-null  bool
 18  order_date          128746 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(14)
memory usage: 17.8+ MB

In [55]:
state_mapping = {
    "Orissa":"Odisha",
    "Rajsthan":"Rajasthan",
    "Rajshthan":"Rajasthan",
    "Rj":"Rajasthan",
    "Pb":"Punjab",
    "Pondicherry":"Puducherry"
}

df_clean["ship_state"] = df_clean["ship_state"].replace(state_mapping)

In [56]:
df_clean.to_csv(
    r"C:\Users\natch\Downloads\amazon_sales_clean.csv",
    index=False
)

In [1]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\natch\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\natch\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\natch\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [57]:
from sqlalchemy import create_engine
import pymysql

engine = create_engine(
    "mysql+pymysql://root:Deepu26062002@localhost:3306/amazon_sales_db"
)

df_clean.to_sql(
    "amazon_sales",
    con=engine,
    if_exists="replace",
    index=False
)

128746